const fundingData = [
  {
    id: "1",
    name: "Government Grant",
    description: "Funding from the government",
    code: "GOV001",
    type: "Grant",
    is_active: true,
  },
  {
    id: "2",
    name: "Private Donation",
    description: "Funds donated by private individuals or organizations",
    code: "PRI002",
    type: "Donation",
    is_active: false,
  },
  {
    id: "3",
    name: "Corporate Sponsorship",
    description: "Sponsorship provided by corporations",
    code: "COR003",
    type: "Sponsorship",
    is_active: true,
  },
  {
    id: "4",
    name: "Research Grant",
    description: "Grant for research projects",
    code: "RES004",
    type: "Grant",
    is_active: true,
  },
  {
    id: "5",
    name: "Community Support",
    description: "Funds from community support initiatives",
    code: "COM005",
    type: "Support",
    is_active: true,
  },
  {
    id: "6",
    name: "Educational Fund",
    description: "Fund for educational purposes",
    code: "EDU006",
    type: "Fund",
    is_active: true,
  },
  {
    id: "7",
    name: "Healthcare Donation",
    description: "Donation for healthcare services",
    code: "HEA007",
    type: "Donation",
    is_active: true,
  },
  {
    id: "8",
    name: "Environmental Grant",
    description: "Grant for environmental protection projects",
    code: "ENV008",
    type: "Grant",
    is_active: false,
  },
  {
    id: "9",
    name: "Sports Sponsorship",
    description: "Sponsorship for sports events",
    code: "SPO009",
    type: "Sponsorship",
    is_active: true,
  },
  {
    id: "10",
    name: "Cultural Fund",
    description: "Fund for cultural activities",
    code: "CUL010",
    type: "Fund",
    is_active: false,
  },
  {
    id: "11",
    name: "Tech Innovation Grant",
    description: "Grant for technology innovation projects",
    code: "TEC011",
    type: "Grant",
    is_active: true,
  },
  {
    id: "12",
    name: "Youth Development",
    description: "Funds for youth development programs",
    code: "YOU012",
    type: "Support",
    is_active: true,
  },
  {
    id: "13",
    name: "Emergency Relief",
    description: "Funds for emergency relief efforts",
    code: "EMR013",
    type: "Relief",
    is_active: false,
  },
  {
    id: "14",
    name: "Animal Welfare Donation",
    description: "Donation for animal welfare organizations",
    code: "ANI014",
    type: "Donation",
    is_active: false,
  },
  {
    id: "15",
    name: "Arts and Culture Sponsorship",
    description: "Sponsorship for arts and culture projects",
    code: "ART015",
    type: "Sponsorship",
    is_active: true,
  },
  {
    id: "16",
    name: "Infrastructure Fund",
    description: "Fund for infrastructure development",
    code: "INF016",
    type: "Fund",
    is_active: false,
  },
  {
    id: "17",
    name: "Public Service Grant",
    description: "Grant for public service projects",
    code: "PUB017",
    type: "Grant",
    is_active: false,
  },
  {
    id: "18",
    name: "Disaster Recovery Fund",
    description: "Fund for disaster recovery efforts",
    code: "DIS018",
    type: "Fund",
    is_active: false,
  },
];

export default fundingData;
