import { DOMESTIC } from "@/shared/enums/domestic";
import { STATUS_PROJECT } from "@/shared/enums/statusProject";
import { SUBMIT_METHOD } from "@/shared/enums/submissionMethod";
import { IBidBond } from "../bid_bond/bidBond.model";
import { IBidDocument } from "../bid_document/bid_document.model";
import { IBiddingResult } from "../biddingResult/biddingResult.model";

export interface IProject {
  id: number;
  children?: IProject[];
  funding_source_id?: number | string;
  tenderer?: string | any;
  investor?: string | any;
  staff_id?: number | string;
  industry_id?: number[];
  procurement_id?: number[];
  selection_method_id?: number | string;
  parent_id?: number | null;
  decision_number?: string;
  name: string;
  is_domestic: DOMESTIC;
  location: string;
  amount?: number;
  total_amount?: number;
  description?: string;
  receiving_place: string;
  bid_submission_start: string;
  bid_submission_end: string;
  bid_opening_date: string;
  start_time: string;
  end_time: string;
  decision_number_approve: string;
  approve_at?: string;
  created_at?: string;
  status: STATUS_PROJECT;
  submission_method?: SUBMIT_METHOD;
  files?: File[];
  fileChildren?: File[];
  decision_number_issued: string;
  upload_time?: string;
  industries?: number[] | any;
  funding_source?: string | any;
  staff?: string | any;
  procurement_categories?: number[] | any;
  selection_method?: string | any;
  attachments?: File[] | any;
  investorName?: string;
  funding_sourceName?: string;
  staffName?: string;
  tendererName?: string;
  arrayIndustry?: string[];
  procurement_category_name?: string[];
  bidding_bond?: IBidBond;
  bidding_result?: IBiddingResult;
  bidding_document?: IBidDocument[];
}
export interface INewProject extends IProject {
  tenderer_id: number | null;
  investor_id: number | null;
  children?: INewProject[];
  selection_methodName?: string;
}
