// ? [key: path]: name
export enum EPageNames {
  "dashboard" = "Bảng điều khiển",
  "orders" = "Orders",
  "update" = "Cập nhật",
  "detail" = "Chi tiết",
  "create" = "Tạo mới",
  "enterprise" = "Doanh nghiệp",
  "project" = "Dự án",
  "staffs" = "Nhân viên",
  "business-activity" = "Loại hình kinh doanh",
  "bidding-fields" = "Lĩnh vực đấu thầu",
  "bidding-types" = "Loại hình đấu thầu",
  "statistical-reports" = "Báo cáo thống kê",
  "industry" = "Ngành kinh doanh",
  "bidding-historys" = "Lịch sử Đấu thầu",
  "bidding-results" = "Kết quả Đấu thầu",
  "bid-document" = "Hồ sơ dự thầu",
  "activity-logs" = "Nhật ký hoạt động",
  "selection-methods" = "Hình thức lựa chọn Nhà thầu",
  "procurement-categories" = "Loại hình mua sắm công",
  "supports" = "Tài khoản hỗ trợ doanh nghiệp",
  "post-catalogs" = "Danh mục bài viết",
  "banners" = "Banner",
  "bid-bond" = "Bão lãnh dự thầu",
  "questions-answers" = "Câu Hỏi/Trả lời",
  "feedback-complaint" = "Phản hồi và Khiếu nại",
  "instructs" = "Hướng dẫn",
  "introductions" = "Giới thiệu",
  "work-progresses" = "Tiến độ dự án",
  "evaluation_criteria" = "Tiêu chí đánh giá",
  "evaluates" = "Đánh giá kết quả dự án",
  "attachment" = "Tài liệu đính kèm",
  "project-approval" = "Phê duyệt dự án"
} 
