// ? [key: path]: name
export enum EPageNames {
  "dashboard" = "Bảng điều khiển",
  "products" = "Products",
  "categories" = "Categories",
  "orders" = "Orders",
  "customers" = "Customers",
  "update" = "Cập nhật",
  "detail" = "Chi tiết",
  "create" = "Tạo mới",
  "enterprise" = "Doanh nghiệp",
  "staffs" = "Nhân viên",
  "business-activity" = "Loại hình hoạt động",
  "bidding-fields" = "Lĩnh vực đấu thầu",
  "bidding-types" = "Loại hình đấu thầu",
  "statistical-reports" = "Báo cáo thống kê",
  "industry" = "Ngành kinh doanh",
  "bidding-historys" = "Lịch sử Đấu thầu",
  "bidding-results" = "Kết quả Đấu thầu",
  "activity-logs" = "Nhật ký hoạt động",
  "selection-methods" = "Hình thức lựa chọn Nhà thầu",
  "banners" = "Banner",
}
