import { IProcurementCategorie } from './../procurementCategorie/procurementCategorie.model';
import { IStaff } from '../account/account.model';
import { IEnterprise } from '../enterprise/enterprise.model';
import { IIndustry } from '../industry/industry.model';
import { ISelectionMethod } from '../selectionMethod/selectionMethod.model';
import { IFundingSource } from './../funding_source/funding_source.model';
import { IEvaluationCriteria } from '../evaluation/evaluation.model';
import { IAttachment } from '../attachment/attachment.model';
export interface ICompareProject {
    id: string;
    name: string;
    value: number;
    project_ids?: number[];
    total_amount: number;
    bidder_count: number;
    duration: number;
    children: ICompareProject[];
    funding_source?: IFundingSource[];
    tenderer?: IEnterprise[];
    investor?: IEnterprise[];
    staff?: IStaff[];
    selection_method?: ISelectionMethod[];
    industries?: IIndustry[];
    procurement_categories?: IProcurementCategorie[];
    attachments?: IAttachment;
    evaluation_criterias?: IEvaluationCriteria[];
    decision_number_issued?: string;
    is_domestic?: string;
    location?: string;
    amount?: string;
    description?: string | null;
    submission_method: string | null;
    receiving_place?: string | null;
    bid_submission_start?: string;
    bid_submission_end?: string;
    bid_opening_date?: string | null;
    start_time?: string;
    end_time?: string;
    approve_at?: string | null;
    decision_number_approve?: string | null;
    status?: string;
}
